CREATE TABLE IF NOT EXISTS isos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL UNIQUE,
  location VARCHAR,
  bucket VARCHAR,
  size INTEGER
);

CREATE TABLE IF NOT EXISTS dirs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  path VARCHAR NOT NULL,
  scan_root_dir_id INTEGER NOT NULL,

  UNIQUE(scan_root_dir_id, path)
);

CREATE TABLE IF NOT EXISTS files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dir_id INTEGER NOT NULL,
  iso_id INTEGER NOT NULL DEFAULT 0,
  name VARCHAR NOT NULL,
  ext VARCHAR NOT NULL,
  size INTEGER NOT NULL,
  hash VARCHAR NOT NULL,
  mod_time TIMESTAMP NOT NULL,

  UNIQUE(dir_id, name)
);